eureka:
  client:
    serviceUrl.defaultZone: 'http://localhost:8761/eureka'

spring:
  cloud.discovery.enabled: false
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:7070/auth/realms/online-shop'
  zipkin.enabled: false
  boot.admin.client.url: 'http://localhost:5050'
