eureka:
  client:
    serviceUrl.defaultZone: 'http://localhost:8761/eureka'

spring:
  cloud.discovery.enabled: true
  zipkin.enabled: false
  boot.admin.client.enabled: false
  boot.admin.client.url: 'http://localhost:5050'
  session:
    store-type: redis
  cache:
    redis:
      time-to-live: 10m
  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/chat_db'
    username: chat_db_admin
    password: ZXadQR
    hikari:
      schema: chat_app_schema
    flyway:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      schemas: ${spring.datasource.hikari.schema}
  data.cassandra:
    keyspace-name: chat_keyspace
    contact-points: '127.0.0.1:9042'
    username: cassandra
    password: ZXadQR
    local-datacenter: "datacenter1"

    schema-action: NONE
    connection:
      connect-timeout: 10000ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:7070/auth/realms/online-shop'

com.rb.alwaysontheroad.chatservice:
  redis:
    host: 'localhost'
    port: 6379
  stomp-broker:
    username: 'chat_admin'
    password: 'ZXadQR'
    client-username: ${com.rb.alwaysontheroad.chatservice.stomp-broker.username}
    client-password: ${com.rb.alwaysontheroad.chatservice.stomp-broker.password}
    v-host: 'chat_vhost'
    host: 'localhost'
    port: 61613